# Generated by Django 2.1 on 2019-05-29 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('StudentName', models.TextField()),
                ('Grade', models.IntegerField()),
                ('Date', models.TextField()),
                ('Concept', models.TextField()),
                ('ConceptProgress', models.IntegerField()),
                ('SubConcept', models.TextField()),
                ('SubConceptProgress', models.IntegerField()),
                ('PerSolved', models.IntegerField()),
                ('AverageTimePerQuestion', models.IntegerField()),
                ('LGD', models.IntegerField()),
                ('LGR', models.IntegerField()),
                ('PerLearningGapResolved', models.TextField()),
                ('comment', models.TextField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_id', models.IntegerField()),
                ('text', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField()),
                ('interv_id', models.IntegerField()),
                ('interv_type', models.IntegerField()),
                ('asgn_to', models.IntegerField()),
                ('follow_up_by', models.TextField()),
                ('interv_status', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
