# Generated by Django 2.1 on 2019-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.TextField()),
                ('Grade', models.TextField()),
                ('Date', models.TextField()),
                ('Concept', models.TextField()),
                ('ConceptProgress', models.TextField()),
                ('SubConcept', models.TextField()),
                ('SubConceptProgress', models.TextField()),
                ('PerSolved', models.TextField()),
                ('AverageTimePerQuestion', models.TextField()),
                ('LGD', models.TextField()),
                ('LGR', models.TextField()),
                ('PerLearningGapResolved', models.TextField()),
                ('comment', models.TextField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
