# Generated by Django 2.1 on 2019-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0002_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='AverageTimePerQuestion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='ConceptProgress',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='Grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='LGD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='LGR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='PerSolved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='SubConceptProgress',
            field=models.IntegerField(),
        ),
    ]
