# Generated by Django 2.1 on 2019-05-28 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0003_auto_20190528_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_stamp', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('cmt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funtoot.Alerts')),
            ],
        ),
    ]
