# Generated by Django 2.1 on 2019-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_id',
            field=models.IntegerField(),
        ),
    ]
