# Generated by Django 2.1 on 2019-05-28 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0005_auto_20190528_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, verbose_name=django.utils.timezone.now),
        ),
    ]
