# Generated by Django 2.1 on 2019-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funtoot', '0006_auto_20190528_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField()),
                ('interv_id', models.IntegerField()),
                ('interv_type', models.IntegerField()),
                ('asgn_to', models.IntegerField()),
                ('follow_up_by', models.TextField()),
                ('interv_status', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
