# Generated by Django 2.2.1 on 2019-06-19 04:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eblity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutor_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('intention', models.CharField(max_length=100)),
                ('absent_present', models.CharField(max_length=15)),
                ('reasonOfAbsence', models.CharField(max_length=100)),
            ],
        ),
    ]
