# Generated by Django 2.2.1 on 2019-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblity', '0002_attendance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Table',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('parent_email', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
