# Generated by Django 2.2.1 on 2019-06-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblity', '0003_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_table',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblity.Student_Table'),
        ),
    ]
