# Generated by Django 2.2.1 on 2019-06-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblity', '0004_auto_20190619_0559'),
        ('eblity', '0003_userprofileinfo'),
    ]

    operations = [
    ]
